"""
Plots "Turning Density" charts for Formula 1 circuits 
based on data generated by "compute_TD_and_LGWTD.py".

Published July 2026

@author: mchmiel21
"""

# import necessary modules
import fastf1
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize, LinearSegmentedColormap
from matplotlib.cm import ScalarMappable
from matplotlib.patches import Patch
import seaborn as sns
import time
import logging
from pathlib import Path

######## function to make and save bar charts for a single year ########
def make_bar_chart_single_year(metric, year):
	# Ensure output directories exist
	Path("Result Images").mkdir(exist_ok=True)
	Path(f"Result Images/Bar Charts").mkdir(exist_ok=True)
	# Handle input differences by metric
	if metric == "TD":
		plot_col = 'Turning Density [deg/km]'
		title_str = f'Turning Density (TD) Ranking of {year} Formula 1 Circuits'
		xlabel_str = 'Degrees Turned per Kilometer of Track [°/km]'
		units_str = '°/km'
		annotation_pad = 50
	elif metric == "LGWTD":
		plot_col = 'Lateral G-Weighted Turning Density [G-deg/km]'
		title_str = f'Lateral G-Weighted Turning Density (LGWTD) Ranking of {year} Formula 1 Circuits'
		xlabel_str = 'Lateral G-Weighted Turning Density [G-°/km]'
		units_str = ' G-°/km'
		annotation_pad = 125
	else:
		print(f'ERROR: Metric {metric} is undefined: options are TD or LGWTD')
		return
	# read data from CSV generated by compute_TD_and_LGWTD.py
	try:
		df_metric_data = pd.read_csv(f'Result CSVs/{year}_F1_TD_and_LGWTD.csv')
	except FileNotFoundError as e:
		print(f"ERROR reading file: {e}")
		return
	
	# Rank order by requested metric
	df_metric_data['Rank'] = df_metric_data[plot_col].rank(ascending=False, method='first').astype(int)
	df_metric_data = df_metric_data.sort_values(by='Rank').reset_index(drop=True)
	# Classify tracks
	# Note: These only currently consider 2024-2026 circuits
	non_permanent_circuits = [
		# Full street circuits
		'Jeddah', 'Monte Carlo', 'Monaco', 'Baku', 'Marina Bay', 'Las Vegas',
		# Temporary/semi-permanent street-style circuits
		'Melbourne', 'Miami Gardens', 'Miami', 'Montréal', 'Madrid'
	]
	# Create a classification column
	df_metric_data['Circuit Type'] = df_metric_data['Circuit'].apply(
		lambda x: 'Non-Permanent' if x in non_permanent_circuits else 'Permanent'
	)
	# Determine color configuration based on metric type
	if metric == "LGWTD":
        # Map values to custom colors for track conditions
		color_palette = {'Dry': '#e10600', 'Wet': '#0066ff'}
		hue_col = 'Track Condition'
	else:
        # Fall back to default Circuit Type mapping
		color_palette = {'Non-Permanent': '#2b2b2b', 'Permanent': '#e10600'}
		hue_col = 'Circuit Type'
	# Create the horizontal bar plot
	sns.set_theme(style="darkgrid")
	plt.figure(figsize=(12, 8))
	ax = sns.barplot(
		x=plot_col,
		y='Circuit',
		hue=hue_col,
		data=df_metric_data,
		palette=color_palette,
		dodge=False,
		order=df_metric_data['Circuit']
	)
	# ensure annotations stay within axes limits
	ax.set_xlim(0, np.ceil((df_metric_data[plot_col].max()+annotation_pad)/annotation_pad)*annotation_pad)
	# Stylize the chart
	plt.title(title_str, fontsize=16, fontweight='bold', pad=20)
	plt.xlabel(xlabel_str, fontsize=14, labelpad=10)
	plt.ylabel('Grand Prix Circuit', fontsize=14)
	plt.legend(title=hue_col, loc='lower right', frameon=True)
	# Add data value labels to the end of each bar
	for p in ax.patches:
		width = p.get_width()
		if width > 0: # Ensure valid bars are labeled
			ax.text(
				width + df_metric_data[plot_col].max() * 0.01, # Position slightly past the end of the bar
				p.get_y() + p.get_height() / 2, # Center vertically in the bar row
				f'{width:.1f}{units_str}',         
				va='center',
				fontsize=10,
				fontweight='bold'
			)
	plt.tight_layout()
	# Save the plot
	plt.savefig(f'Result Images/Bar Charts/{year}_F1_{metric}_bar_chart.png', dpi=450, bbox_inches="tight")
	plt.close()
	# plt.show()

######## function to make and save bar charts comparing multiple years ########
# only plots shared circuits, orders by highest year per circuit
def make_bar_chart_multiple_years(metric, years, rank_by_year):
    import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

def make_bar_chart_multiple_years(metric, years):
    # Ensure output directories exist
    Path("Result Images").mkdir(exist_ok=True)
    Path(f"Result Images/Bar Charts").mkdir(exist_ok=True)
    # Handle input differences by metric
    if metric == "TD":
        plot_col = 'Turning Density [deg/km]'
        title_str = f'Turning Density (TD) Ranking of {", ".join(map(str, years))} F1 Circuits'
        xlabel_str = 'Degrees Turned per Kilometer of Track [°/km]'
        units_str = '°/km'
        annotation_pad = 50
    elif metric == "LGWTD":
        plot_col = 'Lateral G-Weighted Turning Density [G-deg/km]'
        title_str = f'Lateral G-Weighted Turning Density (LGWTD) Ranking of {", ".join(map(str, years))} F1 Circuits'
        xlabel_str = 'Lateral G-Weighted Turning Density [G-°/km]'
        units_str = ' G-°/km'
        annotation_pad = 125
    else:
        print(f'ERROR: Metric {metric} is undefined: options are TD or LGWTD')
        return
    # Read and concatenate data from all requested years
    df_list = []
    # Global dictionary mapping different historical names to a unified key
    circuit_cleaner = {
        'Monte Carlo': 'Monaco',
        'Miami Gardens': 'Miami'
    }
    for year in years:
        try:
            df = pd.read_csv(f'Result CSVs/{year}_F1_TD_and_LGWTD.csv')
            # Normalize circuit name variations across different years immediately upon load
            df['Circuit'] = df['Circuit'].replace(circuit_cleaner)
            df['Year'] = year  # Add year column to identify the data
            df_list.append(df)
        except FileNotFoundError as e:
            print(f"ERROR reading file for year {year}: {e}")
            return
    df_metric_data = pd.concat(df_list, ignore_index=True)
	# Filter data to only include circuits shared between all input years
    total_input_years = len(set(years))
    shared_circuits = df_metric_data.groupby('Circuit')['Year'].nunique()
    shared_circuits = shared_circuits[shared_circuits == total_input_years].index
    df_metric_data = df_metric_data[df_metric_data['Circuit'].isin(shared_circuits)].reset_index(drop=True)
    # Rank order by requested metric based on the maximum value for each circuit across all years
    # Group by Circuit to find the max metric value across all rows, then map it back to create a global rank
    circuit_max_values = df_metric_data.groupby('Circuit')[plot_col].max()
    ranked_circuits = circuit_max_values.sort_values(ascending=False).index
    circuit_rank_map = {circuit: rank for rank, circuit in enumerate(ranked_circuits, start=1)}
    # Merge ranks back to keep consistent ordering across all years
    df_metric_data['Rank'] = df_metric_data['Circuit'].map(circuit_rank_map)
    df_metric_data = df_metric_data.sort_values(by='Rank').reset_index(drop=True)
    # Classify tracks
    # Note: These only currently consider 2024-2026 circuits
    non_permanent_circuits = [
        # Full street circuits
        'Jeddah', 'Monte Carlo', 'Monaco', 'Baku', 'Marina Bay', 'Las Vegas',
        # Temporary/semi-permanent street-style circuits
        'Melbourne', 'Miami Gardens', 'Miami', 'Montréal', 'Madrid'
    ]
    df_metric_data['Circuit Type'] = df_metric_data['Circuit'].apply(
        lambda x: 'Non-Permanent' if x in non_permanent_circuits else 'Permanent'
    )
	# Determine color configuration based on metric type
    if metric == "LGWTD":
        # Map values to custom colors for track conditions
        color_palette = {'Dry': '#e10600', 'Wet': '#0066ff'}
        hue_col = 'Track Condition'
    else:
        # Fall back to default Circuit Type mapping
        color_palette = {'Non-Permanent': '#2b2b2b', 'Permanent': '#e10600'}
        hue_col = 'Circuit Type'
    # Create the grouped horizontal bar plot
    sns.set_theme(style="darkgrid")
    plt.figure(figsize=(14, 10)) 
    # Sort years explicitly in ascending order to force oldest bar to top and newest to bottom
    sorted_years = sorted(years)
    # Note: Hue is now 'Year' to create the multiple bars
    ax = sns.barplot(
        x=plot_col, 
        y='Circuit', 
        hue='Year', 
        hue_order=sorted_years,
        data=df_metric_data, 
        orient='h'
    )
    # Map layout patches safely back to the data table coordinates 
    num_circuits = df_metric_data['Circuit'].nunique()
    num_years = len(sorted_years)
    # Add Year number inside each bar
    for p in ax.patches:
        width = p.get_width()
        if width > 0: # Avoid drawing on empty/missing data
            y_center = p.get_y() + p.get_height() / 2
            # Find which visual group slot (Circuit) and sub-slot (Year) this patch occupies
            circuit_idx = int(round(y_center))
            # Seaborn draws patches hue-by-hue sequentially across the categorical index
            # Find out which hue slice index this patch falls into based on its relative patch position
            patch_idx = ax.patches.index(p)
            year_idx = patch_idx // num_circuits
            year_val = sorted_years[year_idx]
            # Fetch the actual categorical circuit label on the y-axis
            circuit_name = ax.get_yticklabels()[circuit_idx].get_text()
            # Match data row with the calculated circuit name and tracking year
            matched_rows = df_metric_data[
                (df_metric_data['Circuit'] == circuit_name) & 
                (df_metric_data['Year'] == year_val)
            ]
            if not matched_rows.empty:
                row = matched_rows.iloc[0]
                bar_color = row[hue_col]
                # Apply custom classification color dynamically
                p.set_facecolor(color_palette[bar_color])
                # Write the year and metric value inside the bar
                ax.text(
                    5,  # Tiny inset left margin
                    y_center, 
                    f'{year_val}', 
                    ha='left', 
                    va='center', 
                    fontsize=9, 
                    fontweight='bold', 
                    color='white'
                )
                # Append raw metric scores outside the edge bounding box
                ax.text(
                    width + (df_metric_data[plot_col].max() * 0.008), 
                    y_center, 
                    f'{width:.1f}{units_str}', 
                    ha='left', 
                    va='center', 
                    fontsize=9, 
                    fontweight='bold',
                    color='black'
                )
    # ensure annotations stay within axes limits
    max_val = df_metric_data[plot_col].max()
    ax.set_xlim(0, np.ceil((max_val + annotation_pad) / annotation_pad) * annotation_pad)
    # Stylize the chart
    plt.title(title_str, fontsize=16, fontweight='bold', pad=20)
    plt.xlabel(xlabel_str, fontsize=14, labelpad=10)
    plt.ylabel('Grand Prix Circuit', fontsize=14)
    # Overwrite default year legend
    legend_elements = [Patch(facecolor=color, label=label) for label, color in color_palette.items()]
    plt.legend(handles=legend_elements, title=hue_col, loc='lower right', frameon=True)
    plt.tight_layout()
    # Save the plot
    years_str = "-".join(map(str, years))
    plt.savefig(f'Result Images/Bar Charts/{years_str}_F1_{metric}_bar_chart.png', dpi=450, bbox_inches="tight")
    # plt.show()
    plt.close()

######## VISUALIZE LAP XY TRACES COLORED BY SPEED ########
def make_TD_speed_circuit_maps(year):
	# Ensure output directories exist
	Path("Result Images").mkdir(exist_ok=True)
	Path(f"Result Images/Circuit Maps").mkdir(exist_ok=True)
	# read DataFrame from Parquet generated by compute_TD_and_LGWTD.py
	try:
		df_circuit_data = pd.read_parquet(f'Result DataFrame Parquets/{year}_F1_TD_and_LGWTD.parquet')
	except FileNotFoundError as e:
		print(f"ERROR reading file: {e}")
		return
	# Rank data by Turning Density
	df_circuit_data['Rank'] = df_circuit_data['Turning Density [deg/km]'].rank(ascending=False, method='first').astype(int)
	df_circuit_data = df_circuit_data.sort_values(by='Rank').reset_index(drop=True)
	# Number of circuits
	n_circuits = len(df_circuit_data)
	# Grid dimensions of the plot
	n_cols = 4
	n_rows = int(np.ceil(n_circuits / n_cols))
	# Generate subplot structure
	fig, axes = plt.subplots(
		n_rows,
		n_cols,
		figsize=(4.2 * n_cols, 4.4 * n_rows),
		constrained_layout=True
	)
	axes = np.array(axes).flatten()
	# Global speed limits so the colorbar is consistent across all circuits
	vmin = 50
	vmax = 400
	norm = Normalize(vmin=vmin, vmax=vmax)
	# speed_cmap = plt.colormaps['turbo']
	# Custom colormap:
	speed_cmap = LinearSegmentedColormap.from_list(
		'speed_cmap',
		[
			(0.00, "#001041"),  # Very slow: dark blue
			(0.25, '#0057ff'),  # Slow-medium: blue
			(0.45, '#66ccff'),  # Medium: light blue
			(0.55, "#d49100"),  # Fast-ish: orange
			(0.75, "#b90f00"),  # Fast: red
			(1.00, "#690501")   # Fastest: dark red
		]
	)
	# Generate each circuit map
	for idx, row in df_circuit_data.iterrows():
		ax = axes[idx]
		ax.set_facecolor('white')
		ax.grid(False)
		x_trace = np.asarray(row['X Trace'], dtype=float)
		y_trace = np.asarray(row['Y Trace'], dtype=float)
		speed_trace = np.asarray(row['Speed Trace'], dtype=float)
		# Center each circuit around its own origin
		x_plot = x_trace - np.nanmean(x_trace)
		y_plot = y_trace - np.nanmean(y_trace)
		# Explicitly close the plotted trace so the start/finish segment is colored
		x_plot_closed = np.append(x_plot, x_plot[0])
		y_plot_closed = np.append(y_plot, y_plot[0])
		speed_trace_closed = np.append(speed_trace, speed_trace[0])
		# Build line segments from consecutive X/Y points, including final point back to start
		points = np.array([x_plot_closed, y_plot_closed]).T.reshape(-1, 1, 2)
		segments = np.concatenate([points[:-1], points[1:]], axis=1)
		# Use average endpoint speed for each segment
		segment_speeds = 0.5 * (speed_trace_closed[:-1] + speed_trace_closed[1:])
		# Define line collection
		lc = LineCollection(
			segments,
			cmap=speed_cmap,
			norm=norm,
			linewidth=6,
			capstyle='round' # to ensure smooth outer/inner sides of curves
		)
		lc.set_array(segment_speeds)
		ax.add_collection(lc)
		# Set plot limits manually with padding to avoid clipping/overlap
		x_min, x_max = np.nanmin(x_plot), np.nanmax(x_plot)
		y_min, y_max = np.nanmin(y_plot), np.nanmax(y_plot)
		x_range = x_max - x_min
		y_range = y_max - y_min
		padding_fraction = 0.08 # 8% seems to do the trick
		x_padding = padding_fraction * x_range
		y_padding = padding_fraction * y_range
		ax.set_xlim(x_min - x_padding, x_max + x_padding)
		ax.set_ylim(y_min - y_padding, y_max + y_padding)
		# Equal axes to preserve track shape
		ax.set_aspect('equal', adjustable='box')
		# Clean small-multiple look
		ax.set_xticks([])
		ax.set_yticks([])
		for spine in ax.spines.values():
			spine.set_visible(False)
		# Annotate
		# Circuit title plus turning density printed
		circuit_name = row['Circuit']
		deg_per_km = row['Turning Density [deg/km]']
		ax.set_title(
			f"{row['Rank']}. {circuit_name}\n{deg_per_km:.1f}°/km",
			fontsize=26,
			fontweight='bold'
		)
	# Hide unused subplot axes
	for empty_idx in range(n_circuits, len(axes)):
		axes[empty_idx].axis('off')
	# Overall title
	fig.suptitle(
		f'Turning Density Ranking of {year} F1 Circuits',
		fontsize=52,
		fontweight='bold'
	)
	# Shared colorbar
	sm = ScalarMappable(norm=norm, cmap=speed_cmap)
	sm.set_array([])
	# Format the colorbar
	cbar = fig.colorbar(
		sm,
		ax=axes[:n_circuits],
		orientation='horizontal',
		fraction=0.05,
		pad=0.05
	)
	cbar.set_label('Speed [km/h]', fontsize=36)
	# Format colorbar ticks
	speed_ticks = np.linspace(vmin, vmax, 8)
	cbar.set_ticks(speed_ticks)
	cbar.set_ticklabels([f'{tick:.0f}' for tick in speed_ticks])
	cbar.ax.tick_params(labelsize=26)
	# Save and show
	plt.savefig(
		f'Result Images/Circuit Maps/{year}_F1_TD_circuit_maps.png',
		dpi=450,
		bbox_inches='tight'
	)
	plt.close()
	# plt.show()

######## VISUALIZE LAP XY TRACES COLORED BY LATERAL G FORCES ########
def make_LGWTD_gforce_circuit_maps(year):
	# Ensure output directories exist
	Path("Result Images").mkdir(exist_ok=True)
	Path(f"Result Images/Circuit Maps").mkdir(exist_ok=True)
	# read DataFrame from Parquet generated by compute_TD_and_LGWTD.py
	try:
		df_circuit_data = pd.read_parquet(f'Result DataFrame Parquets/{year}_F1_TD_and_LGWTD.parquet')
	except FileNotFoundError as e:
		print(f"ERROR reading file: {e}")
		return
	# Rank data by LGW Turning Density
	df_circuit_data['Rank'] = df_circuit_data['Lateral G-Weighted Turning Density [G-deg/km]'].rank(ascending=False, method='first').astype(int)
	df_circuit_data = df_circuit_data.sort_values(by='Rank').reset_index(drop=True)
	# Number of circuits
	n_circuits = len(df_circuit_data)
	# Grid dimensions of the plot
	n_cols = 4
	n_rows = int(np.ceil(n_circuits / n_cols))
	# Generate subplot structure
	fig, axes = plt.subplots(
		n_rows,
		n_cols,
		figsize=(4.2 * n_cols, 4.4 * n_rows),
		constrained_layout=True
	)
	axes = np.array(axes).flatten()
	# Global speed limits so the colorbar is consistent across all circuits
	Gmin = 0
	Gmax = 6.5
	norm = Normalize(vmin=Gmin, vmax=Gmax)
	latG_cmap = plt.colormaps['afmhot'] # 'hot' might be better? or go 0-6.5?
	# Generate each circuit map
	for idx, row in df_circuit_data.iterrows():
		ax = axes[idx]
		ax.set_facecolor('white')
		ax.grid(False)
		x_trace = np.asarray(row['X Trace'], dtype=float)
		y_trace = np.asarray(row['Y Trace'], dtype=float)
		latG_trace = np.asarray(row['Lateral G-Force Trace'], dtype=float)
		# Center each circuit around its own origin
		x_plot = x_trace - np.nanmean(x_trace)
		y_plot = y_trace - np.nanmean(y_trace)
		# Explicitly close the plotted trace so the start/finish segment is colored
		x_plot_closed = np.append(x_plot, x_plot[0])
		y_plot_closed = np.append(y_plot, y_plot[0])
		latG_trace_closed = np.append(latG_trace, latG_trace[0])
		# Build line segments from consecutive X/Y points, including final point back to start
		points = np.array([x_plot_closed, y_plot_closed]).T.reshape(-1, 1, 2)
		segments = np.concatenate([points[:-1], points[1:]], axis=1)
		# Use average endpoint speed for each segment
		segment_latG = 0.5 * (latG_trace_closed[:-1] + latG_trace_closed[1:])
		# Define line collection
		lc = LineCollection(
			segments,
			cmap=latG_cmap,
			norm=norm,
			linewidth=6,
			capstyle='round' # to ensure smooth outer/inner sides of curves
		)
		lc.set_array(segment_latG)
		ax.add_collection(lc)
		# Set plot limits manually with padding to avoid clipping/overlap
		x_min, x_max = np.nanmin(x_plot), np.nanmax(x_plot)
		y_min, y_max = np.nanmin(y_plot), np.nanmax(y_plot)
		x_range = x_max - x_min
		y_range = y_max - y_min
		padding_fraction = 0.08 # 8% seems to do the trick
		x_padding = padding_fraction * x_range
		y_padding = padding_fraction * y_range
		ax.set_xlim(x_min - x_padding, x_max + x_padding)
		ax.set_ylim(y_min - y_padding, y_max + y_padding)
		# Equal axes to preserve track shape
		ax.set_aspect('equal', adjustable='box')
		# Clean small-multiple look
		ax.set_xticks([])
		ax.set_yticks([])
		for spine in ax.spines.values():
			spine.set_visible(False)
		# Annotate
		# Circuit title plus turning density printed
		circuit_name = row['Circuit']
		Gdeg_per_km = row['Lateral G-Weighted Turning Density [G-deg/km]']
		wet_or_dry = row['Track Condition']
		if wet_or_dry == "Wet":
			wet_or_dry_annotation = " (Wet)"
		else:
			wet_or_dry_annotation = ""
		ax.set_title(
			f"{row['Rank']}. {circuit_name}\n{Gdeg_per_km:.1f} G-°/km{wet_or_dry_annotation}",
			fontsize=26,
			fontweight='bold'
		)
	# Hide unused subplot axes
	for empty_idx in range(n_circuits, len(axes)):
		axes[empty_idx].axis('off')
	# Overall title
	fig.suptitle(
		f'LGWTD Ranking of {year} F1 Circuits',
		fontsize=40,
		fontweight='bold'
	)
	# Shared colorbar
	sm = ScalarMappable(norm=norm, cmap=latG_cmap)
	sm.set_array([])
	cbar = fig.colorbar(
		sm,
		ax=axes[:n_circuits],
		orientation='horizontal',
		fraction=0.05,
		pad=0.05
	)
	cbar.set_label('Lateral Gs', fontsize=36)
	# Format colorbar ticks
	latG_ticks = np.linspace(Gmin, Gmax, int(Gmax*2+1))
	cbar.set_ticks(latG_ticks)
	cbar.set_ticklabels([f'{tick:.1f}' for tick in latG_ticks])
	cbar.ax.tick_params(labelsize=26)
	# Save and show
	plt.savefig(
		f'Result Images/Circuit Maps/{year}_F1_LGWTD_circuit_maps.png',
		dpi=450,
		bbox_inches='tight'
	)
	plt.close()
	# plt.show()

# Call helper functions to make the plots!
if __name__ == "__main__":
	# Create and save bar charts
	make_bar_chart_single_year(metric="TD", year=2026)
	make_bar_chart_single_year(metric="LGWTD", year=2026)
	make_bar_chart_single_year(metric="TD", year=2025)
	make_bar_chart_single_year(metric="LGWTD", year=2025)
	make_bar_chart_single_year(metric="TD", year=2024)
	make_bar_chart_single_year(metric="LGWTD", year=2024)
	
	# Create and save year comparison bar charts
	make_bar_chart_multiple_years(metric="TD", years=[2024, 2025, 2026])
	make_bar_chart_multiple_years(metric="LGWTD", years=[2024, 2025, 2026])
	make_bar_chart_multiple_years(metric="TD", years=[2024, 2025])
	make_bar_chart_multiple_years(metric="LGWTD", years=[2024, 2025])

	# Create and save circuit maps ordered by Turning Density
	# and colored by speed
	make_TD_speed_circuit_maps(year=2026)
	make_TD_speed_circuit_maps(year=2025)
	make_TD_speed_circuit_maps(year=2024)

	# Create and save circuit maps ordered by Lateral G-Weighted Turning Density
	# and colored by lateral G-force
	make_LGWTD_gforce_circuit_maps(year=2026)
	make_LGWTD_gforce_circuit_maps(year=2025)
	make_LGWTD_gforce_circuit_maps(year=2024)
